main_state = initialize_main_state(1,'default');
d=main_state.follower.dynamics;
get_truth('help');
get_truth('magnetic field eci',d);
get_truth('Magnetic field eCi',d);
get_truth("Magnetic field eCi",d);
get_truth("magnetic field lvlh",d);
get_truth("magnetic field vbn",d);
get_truth('magnetic field ecef',d);
get_truth('magnetic field body',d);
get_truth('quat body eci',main_state.follower.dynamics);
get_truth('quat ecef body',main_state.follower.dynamics);
get_truth('quat body body',main_state.follower.dynamics);
get_truth('dcm body eci',main_state.follower.dynamics);
get_truth('rate body eci body',main_state.follower.dynamics);
get_truth('rate body',main_state.follower.dynamics);
%get_truth('rate lvlh',main_state.follower.dynamics);
%get_truth('rate vbn',main_state.follower.dynamics);
get_truth('rate body eci eci',main_state.follower.dynamics);
get_truth('velocity eci',main_state.follower.dynamics);
get_truth('velocity ecef',main_state.follower.dynamics);
get_truth('position eci',main_state.follower.dynamics);
get_truth('position ecef',main_state.follower.dynamics);
get_truth('sat2sun body',d);
get_truth('magnetic field body',d);
get_truth('gravity body',d);
get_truth('total angular momentum body',d);
get_truth('orbital angular momentum body',d);
get_truth('eccentricity vector body',d);
get_truth('wheel rate body',d);
get_truth('antenna body',d);
get_truth('docking face body',d);
get_truth('time',d);
get_truth('fuel mass',d);
get_truth('orbital energy',d);
get_truth('rotational energy',d);
get_truth('semimajor axis',d);
get_truth('eccentricity',d);
get_truth('inclination angle',d);
get_truth('right ascension of the ascending node',d);
get_truth('argument of perigee',d);
get_truth('true anomaly',d);
get_truth('eclipse',d);
get_truth('solar panel area in sun',d);