# Plots the distance between the satellites over time
- type: Plot2D
  x: truth.t.s
  y: truth.leader.hill.dr.norm

# Plots the relative velocity of the satellites over time
- type: Plot2D
  x: truth.t.s
  y: truth.leader.hill.dv.norm

#Plots all three position coordinates in the Hill frame over time
- type: Plot2D
  x: truth.t.s
  y: [truth.leader.hill.dr.x, truth.leader.hill.dr.y, truth.leader.hill.dr.z]

#Plots all three velocity coordinates in the Hill frame over time
- type: Plot2D
  x: truth.t.s
  y: [truth.leader.hill.dv.x, truth.leader.hill.dv.y, truth.leader.hill.dv.z]