summary: "Return the most recent value of a given statefield"
tags: 
  - "Search Statefield Reports"
description: "This is used for searching for the most recent value of a given statefield."
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - name: imei
    in: query
    type: integer
    required: true
    description: The IMEI of the radio
  - name: statefield
    in: query
    type: string
    required: true
    description: The statefield requested
responses: 
  405:
    description: "Invalid input"