summary: "Return the most recent value of a given field from the Iridium report index"
tags: 
  - "Search Iridium Reports"
description: "This is used for searching for the most recent value of a given field."
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - name: imei
    in: query
    type: integer
    required: true
    description: The IMEI of the radio
  - name: field
    in: query
    type: string
    required: true
    description: The field requested
responses: 
  405:
    description: "Invalid input"