name: PSim Bazel Builds

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        sudo apt-get install bazel

    - name: Build and Test with Bazel
      run: |
        bazel build :psim
        
