name: GNC Regression Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m platformio update
        python -m platformio platform install native
        python -m platformio platform install teensy

    - name: Desktop software tests
      run: |
        python -m platformio test --verbose -e github
        
    - name: Teensy build
      run: |
        python -m platformio run --verbose -e teensy35_ci
        python -m platformio run --verbose -e teensy36_ci
